apiVersion: v1
kind: Service
metadata:
  name: nagp-service
spec:
  type: NodePort
  selector:
    app: nagp
  ports:
  - name: port80
    protocol: TCP
    nodePort: {{ .Values.nodePort }}
    port: 80
    targetPort: 80